# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Olympiad_Swift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Olympiad_Swift
  
  # Prerequisite libraries and Analytics
  pod 'Firebase/Core'
  # Realtime Database
  pod 'Firebase/Database'
  # Authentication
  pod 'Firebase/Auth'
  # Crash Reporting
  pod 'Firebase/Crash'

  target 'Olympiad_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Olympiad_SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
