# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Olympiad_Swift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Olympiad_Swift
  
  # Prerequisite libraries and Analytics
  pod 'Firebase/Core'
  # Realtime Database
  pod 'Firebase/Database'
  # Authentication
  pod 'Firebase/Auth'
  # Crash Reporting
  pod 'Firebase/Crash'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/AdMob'

end
